root = "." 
watch_dir = "src"
tmp_dir = "tmp"


[build]
cmd = "go build -o ./tmp/main app/src/main.go"
# bin = "tmp/main migrate up;tmp/main serve"
include_ext = ["go", "tpl", "tmpl", "html","sql"]
exclude_dir = ["public","migration","database/seeder", "deployment", "dockerfiles", "dbdata", "tools", "bin","vendor"]
log = "air.log"
delay = 1000 # ms
args_bin = ["hello", "world"]

[log]
time = false

[color]
# Customize each part's color. If no color found, use the raw app log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true